/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class com_client_DealTask */

#ifndef _Included_com_client_DealTask
#define _Included_com_client_DealTask
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_client_DealTask
 * Method:    getUdpExampleAddr
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_client_DealTask_getUdpExampleAddr
  (JNIEnv *, jobject);

/*
 * Class:     com_client_DealTask
 * Method:    stopCurrentTask
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_client_DealTask_stopCurrentTask
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_client_DealTask
 * Method:    doTask
 * Signature: (JLjava/lang/String;ILjava/lang/String;Ljava/lang/String;Ljava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_com_client_DealTask_doTask
  (JNIEnv *, jobject, jlong, jstring, jint, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
